apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql:latest
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: papsDB
      - name: MYSQL_USER
        value: paps
      - name: MYSQL_PASSWORD
        value: paps
            
  volumes:
  - name: mysql-data
    hostPath:
      path: /data-volume
      type: Directory
